module.exports ={
    NEXT_QUESTION: "NEXT_QUESTION",
    SHOW_ANSWER: "SHOW_ANSWER",
    LOAD_QUIZ: "LOAD_QUIZ",
    LOAD_QUIZ_SUCCESS: "LOAD_QUIZ_SUCCESS",
    LOAD_QUIZ_FAIL: "LOAD_QUIZ_FAIL",
    TOGGLE_VOSOTROS: "TOGGLE_VOSOTROS",
    TOGGLE_IRREGULAR: "TOGGLE_IRREGULAR",
    BEEP: "BEEP"
}