module.exports ={
    NEXT_QUESTION: "NEXT_QUESTION",
    SHOW_ANSWER: "SHOW_ANSWER",
    LOAD_QUIZ: "LOAD_QUIZ",
    LOAD_QUIZ_SUCCESS: "LOAD_QUIZ_SUCCESS",
    LOAD_QUIZ_FAIL: "LOAD_QUIZ_FAIL",
    SUBMIT_ANSWER: "SUBMIT_ANSWER",
    RESET_ANSWER: "RESET_ANSWER",
    SET_VOSOTROS: "SET_VOSOTROS",
    SET_IRREGULAR: "SET_IRREGULAR",
    //INDICATIVE TENSES
    SET_INDICATIVE: "SET_INDICATIVE",
    SET_PRESENT: "SET_PRESENT",
    SET_PRETERITE: "SET_PRETERITE",
    SET_IMPERFECT: "SET_IMPERFECT",
    SET_CONDITIONAL: "SET_CONDITIONAL",
    SET_FUTURE: "SET_FUTURE"
}